name: doctracking
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc:
  bloc:
  meta:
  http:
  equatable:
  cloud_firestore:
  rxdart:
  flutter_datetime_picker:
    git:
      url: https://github.com/ditheshthegreat/flutter_datetime_picker # Repo
      ref: patch-1 # Branch name
  flutter_masked_text:
  intl:
  font_awesome_flutter: ^8.4.0
  google_sign_in: ^4.0.0
  firebase_auth: ^0.15.0+1
  firebase_core:


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito:
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true


